# Generated by Django 5.1.1 on 2024-10-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_deceription',
            new_name='dep_description',
        ),
    ]
