# Generated by Django 5.1.1 on 2024-10-12 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_rename_dep_deceription_departments_dep_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_spec", models.CharField(max_length=255)),
                ("doc_image", models.ImageField(upload_to="doctors")),
                (
                    "doc_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.departments",
                    ),
                ),
            ],
        ),
    ]
